ALTER TABLE rooms
ADD COLUMN IF NOT EXISTS min_normal_power_kw DOUBLE PRECISION NOT NULL DEFAULT 0.0;

ALTER TABLE rooms
ADD COLUMN IF NOT EXISTS max_normal_power_kw DOUBLE PRECISION NOT NULL DEFAULT 2.8;

ALTER TABLE rooms
ADD COLUMN IF NOT EXISTS allow_unattended_power BOOLEAN NOT NULL DEFAULT FALSE;
